# Generated by Django 2.0.7 on 2018-07-15 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='content.Item')),
                ('name', models.CharField(max_length=200)),
                ('start', models.DateTimeField()),
            ],
            bases=('content.item',),
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='content.Item')),
                ('header', models.CharField(max_length=200)),
                ('body', models.TextField()),
            ],
            bases=('content.item',),
        ),
    ]
