# Generated by Django 2.0.7 on 2018-08-30 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='hide_on_mobile',
            field=models.BooleanField(default=False),
        ),
    ]
