# Generated by Django 2.2.6 on 2020-01-27 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='end_registration_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='start_registration_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
