# Generated by Django 2.2.5 on 2019-09-30 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.URLField(blank=True, max_length=600, null=True)),
                ('image_alt', models.CharField(blank=True, max_length=200, null=True)),
                ('user_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('cell', models.CharField(blank=True, max_length=8)),
                ('em_nr', models.CharField(blank=True, max_length=12)),
                ('home_busstop', models.IntegerField(blank=True, null=True)),
                ('gender', models.IntegerField(blank=True, choices=[(1, 'Mann'), (2, 'Kvinne'), (3, 'Annet')], default=2, null=True)),
                ('user_class', models.IntegerField(blank=True, choices=[(1, '1. Klasse'), (2, '2. Klasse'), (3, '3. Klasse'), (4, '4. Klasse'), (5, '5. Klasse')], default=1, null=True)),
                ('user_study', models.IntegerField(blank=True, choices=[(1, 'Dataing'), (2, 'DigFor'), (3, 'DigInc'), (4, 'DigSam')], default=1, null=True)),
                ('allergy', models.CharField(blank=True, max_length=250)),
                ('tool', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
