# Generated by Django 2.2.6 on 2019-11-18 16:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='registered_users_list',
            field=models.ManyToManyField(blank=True, default=None, through='content.UserEvent', to=settings.AUTH_USER_MODEL, verbose_name='registered users'),
        ),
        migrations.AlterField(
            model_name='userevent',
            name='is_on_wait',
            field=models.BooleanField(default=False, verbose_name='waiting list'),
        ),
    ]
