# Generated by Django 2.1.7 on 2019-04-03 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='gallery',
        ),
        migrations.RemoveField(
            model_name='imagegallery',
            name='item_ptr',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='ImageGallery',
        ),
    ]
