# Generated by Django 2.0.7 on 2018-07-29 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
    ]
