# Generated by Django 2.2.6 on 2020-01-27 18:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_start_end_time_registration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='start',
            new_name='start_date',
        ),
        migrations.AddField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='sign_off_deadline',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
