# Generated by Django 2.0.7 on 2018-07-15 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20180715_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='kind',
            field=models.IntegerField(choices=[('news', 0), ('event', 1)], default=0),
            preserve_default=False,
        ),
    ]
