# Generated by Django 2.2.6 on 2019-11-20 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20191118_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_study',
            field=models.IntegerField(blank=True, choices=[(1, 'Dataing'), (2, 'DigFor'), (3, 'DigInc'), (4, 'DigSam'), (5, 'Drift')], default=1, null=True),
        ),
    ]
