# Generated by Django 2.0.7 on 2018-07-28 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20180728_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poster',
            name='action',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='poster',
            name='action_text',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
