# Generated by Django 2.2.5 on 2019-10-03 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name_plural': 'News'},
        ),
        migrations.AddField(
            model_name='event',
            name='closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='limit',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='UserEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_event_id', models.AutoField(primary_key=True, serialize=False)),
                ('is_on_wait', models.BooleanField(default=False)),
                ('has_attended', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.Event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.User')),
            ],
            options={
                'verbose_name': 'User event',
                'verbose_name_plural': 'User events',
                'unique_together': {('user', 'event')},
            },
        ),
        migrations.AddField(
            model_name='event',
            name='registered_users_list',
            field=models.ManyToManyField(blank=True, default=None, through='content.UserEvent', to='content.User'),
        ),
    ]
