# Generated by Django 2.2.6 on 2020-02-06 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_end_date_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='app_token',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
