# Generated by Django 2.0.7 on 2018-07-15 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_item_kind'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='kind',
        ),
    ]
