# Generated by Django 3.0.4 on 2020-03-31 17:30

import uuid

import enumchoicefield.fields
from django.db import migrations, models

import app.common.enums


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0003_challenge_userchallenge"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cheatsheet",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("desc", models.TextField(blank=True, default="")),
                ("creator", models.CharField(max_length=200)),
                (
                    "grade",
                    enumchoicefield.fields.EnumChoiceField(
                        default=app.common.enums.UserClass(1),
                        enum_class=app.common.enums.UserClass,
                        max_length=6,
                    ),
                ),
                (
                    "study",
                    enumchoicefield.fields.EnumChoiceField(
                        default=app.common.enums.UserStudy(1),
                        enum_class=app.common.enums.UserStudy,
                        max_length=7,
                    ),
                ),
                ("course", models.CharField(max_length=200)),
                ("url", models.CharField(max_length=200)),
            ],
            options={"verbose_name_plural": "Cheatsheets",},
        ),
    ]
