# Generated by Django 2.0.7 on 2018-07-28 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_auto_20180728_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.URLField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='poster',
            name='image',
            field=models.URLField(max_length=400, null=True),
        ),
    ]
