# Generated by Django 2.2.5 on 2019-10-01 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_updated_event__user_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='registered_users_list',
            field=models.ManyToManyField(blank=True, default=None, through='content.UserEvent', to='content.User'),
        ),
        migrations.AlterField(
            model_name='userevent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='content.User'),
        ),
    ]
