# Generated by Django 2.0.7 on 2018-08-04 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_auto_20180804_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.URLField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='image_alt',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
