# Generated by Django 2.2.5 on 2019-10-03 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_updated_event__user_event'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name_plural': 'News'},
        ),
        migrations.AlterModelOptions(
            name='userevent',
            options={'verbose_name': 'User event', 'verbose_name_plural': 'User events'},
        ),
        migrations.AlterField(
            model_name='userevent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.User'),
        ),
        migrations.AlterUniqueTogether(
            name='userevent',
            unique_together={('user', 'event')},
        ),
    ]
