# Generated by Django 2.2.5 on 2019-09-30 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_auto_20191001_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='home_busstop',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_class',
            field=models.IntegerField(blank=True, choices=[(1, '1. Klasse'), (2, '2. Klasse'), (3, '3. Klasse'), (4, '4. Klasse'), (5, '5. Klasse')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_study',
            field=models.IntegerField(blank=True, choices=[(1, 'Dataing'), (2, 'DigFor'), (3, 'DigInc'), (4, 'DigSam')], default=1, null=True),
        ),
    ]
