# Generated by Django 2.2.8 on 2020-02-11 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_user_app_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='vipps_transaction_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
