# Generated by Django 2.2.5 on 2019-09-30 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_auto_20191001_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.IntegerField(blank=True, choices=[(1, 'Mann'), (2, 'Kvinne'), (3, 'Annet')], default=0, null=True),
        ),
    ]
