# Generated by Django 3.0.3 on 2020-02-10 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_user_app_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='sign_off_deadline_schedular_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='start_date_schedular_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='start_registration_schedular_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
