# Generated by Django 2.2.8 on 2020-02-11 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_user_vipps_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_TIHLDE_member',
            field=models.BooleanField(default=False),
        ),
    ]
