# Generated by Django 3.0.3 on 2020-02-13 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_auto_20200210_1623'),
        ('content', '0006_user_is_tihlde_member'),
    ]

    operations = [
    ]
