# Generated by Django 3.0.3 on 2020-02-24 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_user_is_tihlde_member'),
        ('content', '0006_auto_20200210_1645'),
    ]

    operations = [
    ]
