# Generated by Django 3.1.1 on 2020-09-14 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0007_add_alumni_to_user_class"),
    ]

    operations = [
        migrations.AddField(
            model_name="userevent",
            name="allow_photo",
            field=models.BooleanField(default=True),
        ),
    ]
