# Generated by Django 3.0.4 on 2020-03-11 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_merge_20200213_1644'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='start_registration_schedular_id',
            new_name='end_date_schedular_id',
        ),
    ]
