# Generated by Django 3.0.4 on 2020-03-11 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_auto_20200311_2246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='start_date_schedular_id',
        ),
        migrations.AddField(
            model_name='event',
            name='evaluate_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
