# Generated by Django 3.1.2 on 2020-10-06 06:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0008_userevent_allow_photo"),
    ]

    operations = [
        migrations.RenameModel("UserEvent", "Registration"),
        migrations.AlterField(
            model_name="event",
            name="registered_users_list",
            field=models.ManyToManyField(
                blank=True,
                default=None,
                through="content.Registration",
                to=settings.AUTH_USER_MODEL,
                verbose_name="registered users",
            ),
        ),
        migrations.AlterModelOptions(
            name="registration",
            options={
                "ordering": ("event", "is_on_wait", "created_at"),
                "verbose_name": "Registration",
                "verbose_name_plural": "Registrations",
            },
        ),
        migrations.RenameField(
            model_name="registration",
            old_name="user_event_id",
            new_name="registration_id",
        ),
    ]
