# Generated by Django 3.1.2 on 2020-10-12 14:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_rename_user_event_to_registration'),
    ]

    operations = [
        migrations.CreateModel(
            name='WikiPost',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.URLField(blank=True, max_length=600, null=True)),
                ('image_alt', models.CharField(blank=True, max_length=200, null=True)),
                ('wikipost_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(null=True, unique=True)),
                ('description', models.CharField(max_length=200)),
                ('content', models.TextField()),
            ],
            options={
                'verbose_name': 'Wiki Post',
                'verbose_name_plural': 'Wiki Posts',
                'ordering': ['created_at'],
            },
        ),
    ]
