# Generated by Django 3.1.2 on 2020-10-16 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_wikipost'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wikipost',
            options={'ordering': ['-created_at'], 'verbose_name': 'Wiki Post', 'verbose_name_plural': 'Wiki Posts'},
        ),
    ]
