# Generated by Django 3.1.2 on 2020-10-18 13:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_wiki_verbose_and_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='image',
            field=models.URLField(blank=True, max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='challenge',
            name='image_alt',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.RenameModel(
            old_name='Challenge',
            new_name='Badge',
        ),
        migrations.RenameModel(
            old_name='UserChallenge',
            new_name='UserBadge',
        ),
        migrations.AlterModelOptions(
            name='badge',
            options={'verbose_name_plural': 'Badges'},
        ),
        migrations.AlterModelOptions(
            name='userbadge',
            options={'verbose_name_plural': 'User Badges'},
        ),
        migrations.RenameField(
            model_name='userbadge',
            old_name='challenge',
            new_name='badge',
        ),
        migrations.AlterModelOptions(
            name='userbadge',
            options={'verbose_name': 'User badge', 'verbose_name_plural': 'User badges'},
        ),
        migrations.AlterModelOptions(
            name='wikipost',
            options={'ordering': ['-created_at'], 'verbose_name': 'Wiki Post', 'verbose_name_plural': 'Wiki Posts'},
        ),
        migrations.RemoveField(
            model_name='badge',
            name='year',
        ),
        migrations.AddField(
            model_name='badge',
            name='description',
            field=models.CharField(default='Beskrivelse', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='badge',
            name='id',
            field=models.UUIDField(auto_created=True, default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userbadge',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_badges', to=settings.AUTH_USER_MODEL),
        ),
    ]
