# Generated by Django 3.1.3 on 2020-11-03 16:29

import app.common.enums
from django.db import migrations, models
import enumchoicefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_add_relative_field_name_in_registartion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cheatsheet',
            name='official',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cheatsheet',
            name='type',
            field=enumchoicefield.fields.EnumChoiceField(default=app.common.enums.CheatsheetType(3), enum_class=app.common.enums.CheatsheetType, max_length=6),
        ),
    ]
