# Generated by Django 3.1.4 on 2021-02-14 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0015_create_model_Page'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='is_continuously_hiring',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='ingress',
            field=models.CharField(blank=True, default='', max_length=800),
        ),
    ]
