# Generated by Django 3.1.4 on 2021-02-14 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0016_update_jobpost_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registration',
            options={'ordering': ('event', 'registration_id', 'is_on_wait', 'created_at'), 'verbose_name': 'Registration', 'verbose_name_plural': 'Registrations'},
        ),
    ]
