# Generated by Django 3.1.4 on 2021-02-23 18:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0018_fix_registration_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortLink',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=600)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='short_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Short link',
                'verbose_name_plural': 'Short links',
            },
        ),
    ]
