# Generated by Django 3.1.7 on 2021-03-22 17:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0020_auto_20210302_1929'),
    ]

    operations = [
        migrations.CreateModel(
            name='Strike',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=200)),
                ('expires_at', models.DateTimeField()),
                ('nr_of_strikes', models.IntegerField(default=1)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_strikes', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='strikes', to='content.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strikes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Strike',
                'verbose_name_plural': 'Strikes',
            },
        ),
    ]
