# Generated by Django 3.1.13 on 2021-08-30 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0022_remove_user_is_tihlde_member'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='message',
            new_name='title',
        ),
        migrations.AddField(
            model_name='notification',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='notification',
            name='link',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
