# Generated by Django 3.1.13 on 2021-09-27 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0023_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='only_allow_prioritized',
            field=models.BooleanField(default=False),
        ),
    ]
