# Generated by Django 3.1.13 on 2021-09-21 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0023_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='evaluate_link',
        ),
    ]
