# Generated by Django 3.1.13 on 2021-09-24 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0024_remove_event_evaluate_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='app_token',
        ),
        migrations.RemoveField(
            model_name='user',
            name='home_busstop',
        ),
    ]
