# Generated by Django 3.1.13 on 2021-09-28 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0024_remove_event_evaluate_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='only_allow_prioritized',
            field=models.BooleanField(default=False),
        ),
    ]
