# Generated by Django 3.1.13 on 2021-10-06 09:32

import app.content.models.user
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0025_remove_user_app_token_and_busstop'),
    ]

    operations = [
        migrations.CreateModel(
            name='StrikesOverview',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Strikes Overview',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('content.user',),
            managers=[
                ('objects', app.content.models.user.UserManager()),
            ],
        ),
    ]
