# Generated by Django 3.1.13 on 2021-10-04 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0026_strikesoverview'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='class_end',
            field=models.IntegerField(choices=[(1, 'First'), (2, 'Second'), (3, 'Third'), (4, 'Forth'), (5, 'Fifth')], default=5),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='class_start',
            field=models.IntegerField(choices=[(1, 'First'), (2, 'Second'), (3, 'Third'), (4, 'Forth'), (5, 'Fifth')], default=1),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='job_type',
            field=models.CharField(choices=[('PART_TIME', 'Deltid'), ('FULL_TIME', 'Fulltid'), ('SUMMER_JOB', 'Sommerjobb'), ('OTHER', 'Andre')], default='OTHER', max_length=30),
        ),
    ]
