# Generated by Django 3.2.8 on 2021-10-19 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0027_jobpost_type_and_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='can_cause_strikes',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='event',
            name='enforces_previous_strikes',
            field=models.BooleanField(default=True),
        ),
    ]
