# Generated by Django 3.2.8 on 2021-10-27 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0029_remove_event_priority'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='strike',
            options={'ordering': ('-created_at',), 'verbose_name': 'Strike', 'verbose_name_plural': 'Strikes'},
        ),
    ]
