# Generated by Django 3.2.9 on 2021-11-03 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0030_alter_strike_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'verbose_name': 'Page', 'verbose_name_plural': 'Pages'},
        ),
        migrations.AddField(
            model_name='page',
            name='position',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
