# Generated by Django 3.2.8 on 2021-11-07 15:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0008_membership_history_related_name'),
        ('content', '0030_alter_strike_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='ContentRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.URLField(blank=True, max_length=600, null=True)),
                ('image_alt', models.CharField(blank=True, max_length=200, null=True)),
                ('preferred_publish_date', models.DateTimeField(editable=False)),
                ('scheduled_publish_date', models.DateTimeField(editable=False)),
                ('status', models.CharField(choices=[('SENT', 'Innsendt'), ('REVIEWED', 'Gjennomgått'), ('APPROVED', 'Godkjent'), ('REJECTED', 'Avslått')], default='SENT', max_length=30)),
                ('recipient_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_requests', to='group.group')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_requests', to=settings.AUTH_USER_MODEL)),
                ('subject_news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='content.news')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
