# Generated by Django 3.2.8 on 2021-11-12 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0032_event_organizer'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='JobPost',
                ),
            ],
            database_operations=[
                migrations.AlterModelTable(
                    name='JobPost',
                    table='career_jobpost',
                ),
            ],
        ),
    ]
