# Generated by Django 3.2.9 on 2021-11-16 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0033_delete_jobpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_study',
            field=models.IntegerField(blank=True, choices=[(1, 'Dataing'), (2, 'DigFor'), (3, 'DigInc'), (4, 'DigSam'), (5, 'Drift'), (6, 'Info')], default=1, null=True),
        ),
    ]
