# Generated by Django 3.2.10 on 2022-01-27 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0035_auto_20211114_1351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='cell',
        ),
    ]
