# Generated by Django 3.2.10 on 2022-01-27 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0036_events_add_cronjob_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='cell',
        ),
    ]
