# Generated by Django 3.2.10 on 2022-01-26 21:38

from django.db import migrations

from app.util.migrations import UpdateContentType


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0036_events_add_cronjob_fields'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Warning',
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='notification',
                    name='user',
                ),
                migrations.DeleteModel(
                    name='Notification',
                ),
            ],
            database_operations=[
                migrations.AlterModelTable(
                    name='Notification',
                    table='communication_notification',
                ),
                UpdateContentType(app='content', model='notification', new_app='communication')
            ],
        ),
    ]
