# Generated by Django 3.2.10 on 2022-01-20 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0036_auto_20220106_1646'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userbadge',
            unique_together={('user', 'badge')},
        ),
    ]
