# Generated by Django 3.2.10 on 2022-01-31 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0036_events_add_cronjob_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='public_event_registrations',
            field=models.BooleanField(default=True),
        ),
    ]
