# Generated by Django 3.2.10 on 2022-02-02 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0037_move_to_communication'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='public_event_registrations',
            field=models.BooleanField(default=True),
        ),
    ]
