# Generated by Django 3.2.10 on 2022-01-26 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0037_delete_warning'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='Notification',
                ),
            ],
            database_operations=[
                migrations.AlterModelTable(
                    name='Notification',
                    table='communication_notification',
                ),
            ],
        )
    ]
