# Generated by Django 3.2.10 on 2022-02-03 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0037_auto_20220127_1919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbadge',
            name='badge',
        ),
        migrations.RemoveField(
            model_name='userbadge',
            name='user',
        ),
        migrations.DeleteModel(
            name='Badge',
        ),
        migrations.DeleteModel(
            name='UserBadge',
        ),
    ]
