# Generated by Django 3.2.10 on 2022-02-03 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0038_user_public_event_registrations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='cell',
        ),
    ]
