# Generated by Django 3.2.10 on 2022-02-04 12:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0039_remove_user_cell'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_news', to=settings.AUTH_USER_MODEL),
        ),
    ]
