# Generated by Django 3.2.10 on 2022-02-04 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0039_remove_user_cell'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbadge',
            name='badge',
        ),
        migrations.RemoveField(
            model_name='userbadge',
            name='user',
        ),
        migrations.DeleteModel(
            name='Badge',
        ),
        migrations.DeleteModel(
            name='UserBadge',
        ),
    ]
