# Generated by Django 3.2.12 on 2022-03-07 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0042_news_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='runned_sign_up_start_notifier',
            field=models.BooleanField(default=False),
        ),
    ]
