# Generated by Django 3.2.12 on 2022-03-07 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0043_event_sign_up_start_notifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sign_up_start_notifications',
            field=models.BooleanField(default=True),
        ),
    ]
