# Generated by Django 3.2.12 on 2022-03-12 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0015_alter_group_type'),
        ('content', '0044_event_runned_sign_up_start_notifier'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriorityPool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='priority_pools', to='content.event')),
                ('groups', models.ManyToManyField(related_name='event_priority_pools', to='group.Group')),
            ],
            options={
                'verbose_name_plural': 'Priority Pools',
            },
        ),
    ]
