# Generated by Django 3.2.12 on 2022-03-19 18:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0045_prioritypool'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='interested_users',
            field=models.ManyToManyField(related_name='interested_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
