# Generated by Django 3.2.12 on 2022-03-23 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0046_event_favorite_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Toddel',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('edition', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('image', models.URLField(max_length=600)),
                ('pdf', models.URLField(max_length=600)),
                ('published_at', models.DateField()),
            ],
            options={
                'verbose_name': 'Töddel',
                'verbose_name_plural': 'Töddel',
                'ordering': ('-edition',),
            },
        ),
    ]
