# Generated by Django 3.2.12 on 2022-03-23 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0047_toddel'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='slack_user_id',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
