# Generated by Django 4.0.4 on 2022-04-28 19:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0048_user_slack_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='favorite_users',
            field=models.ManyToManyField(blank=True, related_name='favorite_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
