# Generated by Django 4.0.4 on 2022-04-29 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0049_alter_event_favorite_users'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('first_name', 'last_name')},
        ),
    ]
