# Generated by Django 4.1.2 on 2022-10-13 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0051_registration_priorities_and_user_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="accepts_event_rules",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="allows_photo_by_default",
            field=models.BooleanField(default=True),
        ),
    ]
