# Generated by Django 4.0.8 on 2023-09-25 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emoji', '0001_initial'),
        ('content', '0052_event_rules_and_photo_in_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='emojis_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='news',
            name='reactions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reactions', to='emoji.reaction'),
        ),
    ]
