# Generated by Django 4.0.8 on 2023-09-01 06:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0052_event_rules_and_photo_in_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='contact_person',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
