# Generated by Django 4.0.8 on 2023-04-22 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0052_event_rules_and_photo_in_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='user',
            name='feide_id',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
