# Generated by Django 4.2.5 on 2023-10-08 20:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0053_event_contact_person"),
    ]

    operations = [
        migrations.CreateModel(
            name="QRCode",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("image", models.URLField(blank=True, max_length=600, null=True)),
                ("image_alt", models.CharField(blank=True, max_length=200, null=True)),
                ("name", models.CharField(max_length=50)),
                ("url", models.URLField(max_length=600)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qr_codes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "qr_code",
                "verbose_name_plural": "qr_codes",
            },
        ),
    ]
