# Generated by Django 4.0.8 on 2023-09-26 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0053_news_emojis_allowed_news_reactions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='reactions',
        ),
    ]
