# Generated by Django 4.2.5 on 2023-10-17 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0053_event_contact_person"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="emojis_allowed",
            field=models.BooleanField(default=False),
        ),
    ]
