# Generated by Django 4.2.5 on 2023-10-21 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0054_qrcode"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="qrcode",
            name="url",
        ),
        migrations.AddField(
            model_name="qrcode",
            name="content",
            field=models.CharField(default=None, max_length=600),
            preserve_default=False,
        ),
    ]
