# Generated by Django 4.0.8 on 2023-09-26 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0054_event_allow_comments_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-created_at',)},
        ),
    ]
