# Generated by Django 4.0.8 on 2023-10-16 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0055_rename_user_comment_author_remove_comment_event_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='allow_comments',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='news',
            name='allow_comments',
            field=models.BooleanField(default=True),
        ),
    ]
