# Generated by Django 4.2.5 on 2023-11-15 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0055_qrcode"),
    ]

    operations = [
        migrations.AddField(
            model_name="registration",
            name="created_by_admin",
            field=models.BooleanField(default=False),
        ),
    ]
