# Generated by Django 4.0.8 on 2023-10-06 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0055_alter_comment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('created_at',)},
        ),
        migrations.AddField(
            model_name='news',
            name='allow_comments',
            field=models.BooleanField(default=True),
        ),
    ]
