# Generated by Django 4.0.8 on 2023-10-07 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0056_alter_comment_options_news_allow_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='indent_level',
            field=models.IntegerField(default=0),
        ),
    ]
