# Generated by Django 4.2.5 on 2023-12-15 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0056_registration_created_by_admin"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="emojis_allowed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="news",
            name="emojis_allowed",
            field=models.BooleanField(default=False),
        ),
    ]
