# Generated by Django 4.2.5 on 2023-12-17 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0054_registration_payment_expiredate"),
        ("content", "0057_event_emojis_allowed_news_emojis_allowed"),
    ]

    operations = []
