# Generated by Django 4.2.5 on 2024-01-29 17:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0058_merge_20231217_2155"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserBio",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=50)),
                ("gitHub_link", models.URLField(blank=True, max_length=300, null=True)),
                (
                    "linkedIn_link",
                    models.URLField(blank=True, max_length=300, null=True),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bio",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
