# Generated by Django 4.2.5 on 2024-04-08 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0059_minute"),
    ]

    operations = [
        migrations.AddField(
            model_name="minute",
            name="tag",
            field=models.CharField(
                choices=[("Møtereferat", "Minute"), ("Dokument", "Document")],
                default="Møtereferat",
                max_length=50,
            ),
        ),
    ]
