# Generated by Django 4.2.5 on 2024-02-01 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0059_userbio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userbio",
            name="description",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
