# Generated by Django 4.2.5 on 2024-01-22 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0059_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="comments_allowed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="news",
            name="comments_allowed",
            field=models.BooleanField(default=False),
        ),
    ]
