# Generated by Django 4.2.5 on 2024-02-19 16:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0060_alter_userbio_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="userbio",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userbio",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
