# Generated by Django 4.2.5 on 2024-02-21 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0061_userbio_created_at_userbio_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userbio",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bio",
                to=settings.AUTH_USER_MODEL,
                unique=True,
            ),
        ),
    ]
