# Generated by Django 4.2.5 on 2024-02-21 13:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0062_alter_userbio_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userbio",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bio",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
