# Generated by Django 4.2.5 on 2024-02-26 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0063_alter_userbio_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userbio",
            name="description",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
