# Generated by Django 4.2.5 on 2024-04-16 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0060_minute_tag"),
        ("content", "0064_alter_userbio_description"),
    ]

    operations = []
