# Generated by Django 4.2.5 on 2024-09-13 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("group", "0018_fine_defense"),
        ("content", "0066_minute_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="minute",
            name="group",
            field=models.ForeignKey(
                blank=True,
                choices=[("Drift", "Drift"), ("Index", "Index")],
                default="Index",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="meeting_minutes",
                to="group.group",
            ),
        ),
    ]
