# Generated by Django 4.2.5 on 2024-09-20 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0067_alter_minute_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cheatsheet",
            name="grade",
            field=models.CharField(
                choices=[
                    ("FIRST", "1. Klasse"),
                    ("SECOND", "2. Klasse"),
                    ("THIRD", "3. Klasse"),
                    ("FOURTH", "4. Klasse"),
                    ("FIFTH", "5. Klasse"),
                    ("ALUMNI", "Alumni"),
                ],
                default="FIRST",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="cheatsheet",
            name="study",
            field=models.CharField(
                choices=[
                    ("DATAING", "Dataingeniør"),
                    ("DIGFOR", "Digital forretningsutvikling"),
                    ("DIGINC", "Digital infrastruktur og cybersikkerhet"),
                    ("DIGSAM", "Digital samhandling"),
                    ("DRIFT", "Drift"),
                    ("INFO", "Informasjonsbehandling"),
                ],
                default="DATAING",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="cheatsheet",
            name="type",
            field=models.CharField(
                choices=[
                    ("FILE", "Fil"),
                    ("GITHUB", "GitHub"),
                    ("LINK", "Link"),
                    ("OTHER", "Annet"),
                ],
                default="LINK",
                max_length=50,
            ),
        ),
    ]
