# Generated by Django 4.2.16 on 2024-09-27 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0068_alter_cheatsheet_grade_alter_cheatsheet_study_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="public_profile",
            field=models.BooleanField(default=True),
        ),
    ]
