notifications:
  email: false

language: python # => 1

# safelist
branches:
  only:
  - master
  - Ops
  - dev

python: # => 2
  - "3.6"
services: # => 3
  - mysql
env: # => 4
  - DJANGO=2.1.7 
  - DB=mysql
install: # => 5
  - pip install pipenv
  - pipenv install
before_script: # => 6
  - mysql -e 'create database test;' -u root

script: # => 7
  - coverage run --source='.' manage.py test

after_script:
  - codecov


#services: 
#  - docker 

# command to install docker-compose
#before_script:
#  - pip install docker-compose

# command to run tests
#script:
#  - docker-compose run app sh -c "coverage run --source='.' manage.py test"