notifications:
  email: false

# code language
language: python
python:
  - "3.6"

# safelist
branches:
  only:
  - master
  - Ops

services: 
  - docker

# command to install docker-compose
before_script:
  - pip install docker-compose

# command to run tests
script:
  - docker-compose run app sh -c "coverage run --source='.' manage.py test"

  