coverage:
  status:
    project:
      default:
        threshold: 0%
    patch:
      default:
        threshold: 0%
  ignore:
    - manage.py
    - app/settings.py
    - **/apps.py
    - **/tests.py
    - **/wsgi.py
    - **/asgi.py
    - **/test**.py
    - **/migrations
    - **/__init__.py
