version: '3'

volumes:
  local_mysql_data: {}

services:
  lepton_db:
    image: mysql:5.7
    container_name: lepton_db
    volumes:
      - local_mysql_data:/var/lib/mysql
    restart: always
    env_file:
      - ./.envs/.local/.mysql
    ports:
      - '3306:3306'

  phpmyadmin:
    depends_on:
      - lepton_db
    image: phpmyadmin/phpmyadmin
    restart: always
    env_file:
      - ./.envs/.local/.phpmyadmin
    ports:
      - '8080:80'

  web:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: lepton_local_web
    container_name: web
    depends_on:
      - lepton_db
    volumes:
      - .:/usr/src
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.mysql
    ports:
      - "8000:8000"
    command: /start
