version: '3.8'

# Config file for registry settings in Azure App Service dev

services:
  web:
    image: leptondevregistry.azurecr.io/lepton:latest
    container_name: web
    ports:
      - 8000:8000
  celery:
    image: leptondevregistry.azurecr.io/lepton:latest
    container_name: celery
    entrypoint: []
    command: celery -A app worker -E -l info --without-heartbeat --without-gossip --without-mingle
  flower:
    image: leptondevregistry.azurecr.io/lepton:latest
    container_name: flower
    entrypoint: []
    command: celery -A app flower --url_prefix=flower/admin
    ports:
      - 5555:5555
    depends_on:
      - celery
