version: '3'

services:
  db:
    image: mysql:5.7
    platform: linux/x86_64
    container_name: db
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=dev
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=nettside-dev

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password

  web: &web
    build:
      context: .
      dockerfile: compose/Dockerfile
    env_file:
      - ./.envs/.local
    image: web
    container_name: web
    restart: on-failure
    entrypoint: /wait-for-mysql
    command: python manage.py runserver 0.0.0.0:8000
    platform: linux/amd64
    volumes:
      - .:/usr/src/
    ports:
      - "8000:8000"
    depends_on:
      - db

  celery:
    <<: *web
    image: celery
    container_name: celery
    entrypoint: []
    command: celery -A app worker -l info --without-heartbeat --without-gossip --without-mingle
    ports: []
