version: '3'

services:
  db:
    image: mysql:5.7
    container_name: db
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=dev
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=nettside-dev

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password

  web: &web
    env_file:
      - .env
    build: .
    image: web
    container_name: web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/
    expose:
      - 8000
    depends_on:
      - db

  celery:
    <<: *web
    image: celery
    container_name: celery
    command: celery -A app worker -l info --without-heartbeat --without-gossip --without-mingle
    ports: []
    depends_on:
      - rabbitmq

  flower:
    image: mher/flower:0.9.5
    container_name: flower
    command: ['flower', '--broker=amqp://rabbitmq:5672', '--port=5555', '--url-prefix=flower']
    expose:
      - 5555
    depends_on:
      - rabbitmq

  # For testing purposes only
  rabbitmq:
    container_name: rabbitmq
    hostname: rabbitmq
    image: rabbitmq:latest
    ports:
      - "5672:5672"
    restart: on-failure

  nginx:
    container_name: nginx
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - flower
