# TODO: static files
events {}

http {
  server {
    listen 80;
    # server_name localhost;
    access_log                /dev/stdout;
    error_log                 /dev/stderr info;

    # other configs

    # Handle noisy favicon.ico messages in nginx
     location = /favicon.ico {
        return 204;
        access_log     off;
        log_not_found  off;
    }

    location /static/ {
        alias /app/static/;
    }

    location /media/ {
        alias /app/media/;
    }

    location / {
        # checks for static file, if not found proxy to app
        try_files $uri @proxy_to_app;
    }
    location @proxy_to_app {
        proxy_pass http://web:8000;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Host $server_name;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host $host;
        proxy_redirect off;
    }

    # TODO: Auth: https://testdriven.io/blog/flower-nginx/
    location /flower {
        proxy_pass http://flower:5555;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host $host;
    }

  }
}
