# Generated by Django 4.2.5 on 2023-11-06 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blitzed", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pongmatch",
            old_name="prev_match",
            new_name="future_match",
        ),
    ]
