# Generated by Django 4.2.5 on 2023-10-16 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blitzed", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DrinkingGame",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("image", models.URLField(blank=True, max_length=600, null=True)),
                ("image_alt", models.CharField(blank=True, max_length=200, null=True)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("icon", models.URLField(max_length=600)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
