# Generated by Django 4.2.5 on 2023-11-06 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("blitzed", "0002_rename_prev_match_pongmatch_future_match"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pongmatch",
            name="future_match",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="blitzed.pongmatch",
            ),
        ),
    ]
