# Generated by Django 4.2.5 on 2023-10-16 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blitzed", "0002_drinkinggame"),
    ]

    operations = [
        migrations.AlterField(
            model_name="drinkinggame",
            name="icon",
            field=models.URLField(blank=True, max_length=600, null=True),
        ),
    ]
