# Generated by Django 3.1.13 on 2021-10-05 17:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0024_remove_event_evaluate_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(default=uuid.uuid4)),
                ('picture', models.URLField(max_length=300)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('picture_alt', models.CharField(blank=True, max_length=100)),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.event')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
