# Generated by Django 3.1.13 on 2021-10-12 15:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0026_strikesoverview'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('picture', models.URLField(max_length=300)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('picture_alt', models.CharField(blank=True, max_length=100)),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.event')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
