# Generated by Django 4.0.4 on 2022-09-29 17:05

from django.db import migrations, models
import uuid

albums = []

def save_pk(apps, schema_editor):
    Picture = apps.get_model('gallery', 'Picture')
    Album = apps.get_model('gallery', 'Album')
    
    for album in Album.objects.all():
        pic_ids = []
        album.id = uuid.uuid4()
        album.save()
        for picture in Picture.objects.filter(album=album): 
            pic_ids.append(picture.id)

        albums.append({
            'album': album,
            'pic_ids': pic_ids,
        })

def update_pk(apps, schema_editor):
    Picture = apps.get_model('gallery', 'Picture')
    
    for album in albums.get('album'):
        for pic_id in album.get('pic_ids'):
            pic = Picture.objects.get(id=pic_id)
            pic.album = album
            pic.save()

class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='id',
            field=models.UUIDField(unique=True, null=True, default=None),
        ),
        migrations.RunPython(save_pk),
        migrations.RemoveField(
            model_name='picture',
            name='album',
        ),
        migrations.AlterField(
            model_name='album',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name='album',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, null=False, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='picture',
            name='album',
            field=models.ForeignKey(to='gallery.album', on_delete=models.SET_NULL, null=True),
        ),
        migrations.RunPython(update_pk),
    ]
