# Generated by Django 3.1.13 on 2021-09-21 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='event',
        ),
    ]
