# Generated by Django 4.0.4 on 2022-09-29 17:05

from cmath import pi
from django.db import migrations, models
import uuid

pictures = []

def get_fk(apps, schema_editor):
    Picture = apps.get_model('gallery', 'Picture')

    for picture in Picture.objects.all():
        pictures.append(picture)

def insert_fk(apps, schema_editor):
    Album = apps.get_model('gallery', 'Album')

    for picture in pictures:
        for album in Album.objects.all():
            if (picture.album.slug == album.slug):
                picture.album.id = album.id

class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(get_fk),
        migrations.RemoveField(
            model_name='picture',
            name='album',
        ),
        migrations.AlterField(
            model_name='album',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.AddField(
            model_name='album',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='picture',
            name='album',
            field=models.ForeignKey(to='gallery.album', on_delete=models.SET_NULL, null=True),
        ),
        migrations.RunPython(insert_fk),
    ]
