# Generated by Django 3.1.13 on 2021-10-01 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0023_notification'),
        ('gallery', '0002_remove_picture_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.event'),
        ),
    ]
