# Generated by Django 5.1.1 on 2024-11-16 20:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="oauthrequest",
            name="expires",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 11, 16, 21, 26, 11, 566915)
            ),
        ),
    ]
