# Generated by Django 2.2.6 on 2019-11-19 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Connection',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
    ]
