# Generated by Django 5.1.1 on 2024-11-16 20:27

import app.authentication.models.oauth
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_oauthrequest_expires"),
    ]

    operations = [
        migrations.AlterField(
            model_name="oauthrequest",
            name="expires",
            field=models.DateTimeField(
                default=app.authentication.models.oauth.now_plus_5_minutes
            ),
        ),
    ]
