# Generated by Django 4.2.5 on 2024-10-21 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="feedback",
            options={"ordering": ("-created_at",)},
        ),
        migrations.AddField(
            model_name="bug",
            name="Browser",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AddField(
            model_name="bug",
            name="Platform",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AddField(
            model_name="bug",
            name="Url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
