# Generated by Django 4.2.5 on 2024-10-21 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0002_alter_feedback_options_bug_browser_bug_platform_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bug",
            old_name="Browser",
            new_name="browser",
        ),
        migrations.RenameField(
            model_name="bug",
            old_name="Platform",
            new_name="platform",
        ),
        migrations.RenameField(
            model_name="bug",
            old_name="Url",
            new_name="url",
        ),
    ]
