# Generated by Django 5.1.1 on 2025-01-20 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0003_rename_browser_bug_browser_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="emojis_allowed",
            field=models.BooleanField(default=True),
        ),
    ]
