# Generated by Django 5.1.1 on 2025-01-27 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0004_feedback_emojis_allowed"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="image",
            field=models.URLField(blank=True, max_length=600, null=True),
        ),
        migrations.AddField(
            model_name="feedback",
            name="image_alt",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
