# Generated by Django 5.1.1 on 2025-01-27 18:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0005_feedback_image_feedback_image_alt"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Assignee",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("assignee_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "feedback",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignee_feedbacks",
                        to="feedback.feedback",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Assignee",
                "verbose_name_plural": "Assignees",
                "ordering": ("feedback", "created_at"),
                "unique_together": {("user", "feedback")},
            },
        ),
        migrations.AddField(
            model_name="feedback",
            name="assignees",
            field=models.ManyToManyField(
                blank=True,
                default=None,
                related_name="authored_feedbacks",
                through="feedback.Assignee",
                to=settings.AUTH_USER_MODEL,
                verbose_name="assigned users",
            ),
        ),
    ]
