# Generated by Django 5.1.1 on 2025-01-27 18:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0006_assignee_feedback_assignees"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="assignees",
            field=models.ManyToManyField(
                blank=True,
                default=None,
                related_name="assigned_feedbacks",
                through="feedback.Assignee",
                to=settings.AUTH_USER_MODEL,
                verbose_name="assigned users",
            ),
        ),
    ]
