# Generated by Django 3.2.12 on 2022-04-21 15:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomEmoji',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.URLField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='CustomShortName',
            fields=[
                ('value', models.CharField(max_length=32, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='Det er bare tillatt med små bokstaver og understrek.', regex='[a-z_]+')])),
                ('emoji', models.ForeignKey(auto_created=True, on_delete=django.db.models.deletion.CASCADE, related_name='short_names', to='emoji.customemoji')),
            ],
        ),
    ]
