# Generated by Django 4.0.8 on 2023-09-18 18:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0052_event_rules_and_photo_in_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('emoji', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserToddelReactionUnicode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('emoji', models.CharField(max_length=60)),
                ('toddel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.toddel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserNewsReactionUnicode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('emoji', models.CharField(max_length=60)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_reactions', to='content.news')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='usertoddelreactionunicode',
            constraint=models.UniqueConstraint(fields=('user', 'toddel'), name='unique together: user and toddel'),
        ),
        migrations.AddConstraint(
            model_name='usernewsreactionunicode',
            constraint=models.UniqueConstraint(fields=('user', 'news'), name='unique together: user and news'),
        ),
    ]
