# Generated by Django 4.0.8 on 2023-02-06 15:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0052_event_rules_and_photo_in_user'),
        ('emoji', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usernewsreaction',
            options={'verbose_name': 'Reaction', 'verbose_name_plural': 'Reactions'},
        ),
        migrations.AlterUniqueTogether(
            name='usernewsreaction',
            unique_together={('user', 'news')},
        ),
    ]
