# Generated by Django 4.0.8 on 2023-09-27 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emoji', '0002_reaction_content_type_reaction_object_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reaction',
            old_name='id',
            new_name='reaction_id',
        ),
    ]
