# Generated by Django 4.0.8 on 2023-09-28 15:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('emoji', '0003_rename_id_reaction_reaction_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reaction',
            unique_together={('user', 'object_id', 'content_type')},
        ),
    ]
