# Generated by Django 4.0.8 on 2023-03-06 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0052_event_rules_and_photo_in_user'),
        ('emoji', '0004_usertoddelreaction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsEmojis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('emoji', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='emoji.customemoji')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.news')),
            ],
        ),
        migrations.AddConstraint(
            model_name='newsemojis',
            constraint=models.UniqueConstraint(fields=('news', 'emoji'), name='unique together: news and emoji'),
        ),
    ]
