# Generated by Django 4.0.8 on 2023-03-13 18:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0052_event_rules_and_photo_in_user'),
        ('emoji', '0005_newsemojis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsemojis',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emojis', to='content.news'),
        ),
        migrations.AlterField(
            model_name='usernewsreaction',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_reactions', to='content.news'),
        ),
        migrations.AlterField(
            model_name='usernewsreaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to=settings.AUTH_USER_MODEL),
        ),
    ]
