# Generated by Django 4.0.8 on 2023-04-17 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0052_event_rules_and_photo_in_user'),
        ('emoji', '0006_alter_newsemojis_news_alter_usernewsreaction_news_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToddelEmojis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('emoji', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='emoji.customemoji')),
                ('toddel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emojis', to='content.toddel')),
            ],
        ),
        migrations.AddConstraint(
            model_name='toddelemojis',
            constraint=models.UniqueConstraint(fields=('toddel', 'emoji'), name='unique together: toddel and emoji'),
        ),
    ]
