name: Feature request
description: Request new features to be added
labels: [feature]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!
  - type: textarea
    id: what-happened
    attributes:
      label: Feature request
      description: |
        Let us know what functionality you'd like to see in Lepton and what is your use case.
    validations:
      required: true
