# Generated by Django 3.1.2 on 2020-10-22 17:24

import app.forms.enums
from django.db import migrations, models
import django.db.models.deletion
import enumchoicefield.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0012_badges'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventForm',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('form_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('type', enumchoicefield.fields.EnumChoiceField(default=app.forms.enums.FormType(2), enum_class=[app.forms.enums.FormType(2), app.forms.enums.FormType(3)], max_length=10)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.event')),
            ],
            options={
                'verbose_name': 'Event form',
                'verbose_name_plural': 'Event forms',
                'unique_together': {('event', 'type')},
            },
        ),
    ]
