# Generated by Django 3.1.7 on 2021-03-16 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_text',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='answer',
            name='selected_options',
            field=models.ManyToManyField(blank=True, related_name='answers', to='forms.Option'),
        ),
    ]
