# Generated by Django 3.1.13 on 2021-09-19 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_answer_rel_name_to_option_and_one_off_default_answer_text_'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='option',
            options={'ordering': ['title', 'id']},
        ),
    ]
