# Generated by Django 3.1.13 on 2021-10-05 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_sort_options_in_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='field',
            options={'ordering': ('order',)},
        ),
        migrations.AlterModelOptions(
            name='option',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='field',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False, verbose_name='order'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='option',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False, verbose_name='order'),
            preserve_default=False,
        ),
    ]
