# Generated by Django 3.2.8 on 2021-10-18 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_sort_options_in_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
