# Generated by Django 3.2.8 on 2021-10-24 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_form_template'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='field',
            options={'ordering': ('order',)},
        ),
        migrations.AlterModelOptions(
            name='option',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='field',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=1, editable=False, verbose_name='order'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='option',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=5, editable=False, verbose_name='order'),
            preserve_default=False,
        ),
    ]
