# Generated by Django 3.2.9 on 2021-12-21 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0007_groupform'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupform',
            name='can_submit_multiple',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='groupform',
            name='is_open_for_submissions',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='groupform',
            name='only_for_group_members',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='submission',
            unique_together=set(),
        ),
    ]
