# Generated by Django 3.2.10 on 2021-12-22 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0007_groupform'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='form',
            options={'ordering': ('title',), 'verbose_name': 'Form', 'verbose_name_plural': 'Forms'},
        ),
        migrations.AddField(
            model_name='groupform',
            name='can_submit_multiple',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='groupform',
            name='is_open_for_submissions',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='groupform',
            name='only_for_group_members',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='submission',
            unique_together=set(),
        ),
    ]
