# Generated by Django 3.2.9 on 2021-12-20 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0007_groupform'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='submission',
            unique_together=set(),
        ),
    ]
