# Generated by Django 3.2.10 on 2022-02-03 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0008_add_groupform_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='title',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='form',
            name='title',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='option',
            name='title',
            field=models.CharField(default='', max_length=400),
        ),
    ]
