# Generated by Django 3.2.12 on 2022-02-17 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0009_longer_form_titles'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupform',
            name='email_receiver_on_submit',
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
    ]
