# Generated by Django 4.2.5 on 2023-11-20 18:24

import app.forms.enums
from django.db import migrations
import enumchoicefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0011_alter_form_polymorphic_ctype"),
    ]

    operations = [
        migrations.AlterField(
            model_name="field",
            name="type",
            field=enumchoicefield.fields.EnumChoiceField(
                default=app.forms.enums.FormFieldType(1),
                enum_class=app.forms.enums.FormFieldType,
                max_length=16,
            ),
        ),
    ]
