# Generated by Django 4.2.5 on 2024-09-20 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0011_alter_form_polymorphic_ctype"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventform",
            name="type",
            field=models.CharField(
                choices=[("SURVEY", "Survey"), ("EVALUATION", "Evaluation")],
                default="SURVEY",
                max_length=40,
            ),
        ),
    ]
