# Generated by Django 4.2.5 on 2024-09-20 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0012_alter_eventform_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="field",
            name="type",
            field=models.CharField(
                choices=[
                    ("TEXT_ANSWER", "Text answer"),
                    ("MULTIPLE_SELECT", "Multiple select"),
                    ("SINGLE_SELECT", "Single select"),
                ],
                default="TEXT_ANSWER",
                max_length=40,
            ),
        ),
    ]
