# Generated by Django 4.2.16 on 2024-10-01 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0013_alter_field_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="form",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
    ]
