# Generated by Django 3.2.10 on 2022-01-26 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0001_add_mail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.CharField(max_length=400, null=True)),
                ('type', models.IntegerField(choices=[(0, 'Error'), (1, 'Warning'), (2, 'Message')], default=0, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
