# Generated by Django 3.2.10 on 2022-01-26 20:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('communication', '0002_warning'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='Notification',
                    fields=[
                        ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('title', models.CharField(max_length=150)),
                        ('description', models.TextField(blank=True, default='')),
                        ('link', models.CharField(blank=True, max_length=150, null=True)),
                        ('read', models.BooleanField(default=False)),
                        ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        'abstract': False,
                    },
                ),
            ],
            # Table already exists. See app\content\migrations\0038_delete_notification.py
            database_operations=[],
         ),
    ]
