# Generated by Django 3.2.12 on 2022-03-24 18:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('communication', '0003_notification_user_related_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNotificationSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notification_type', models.CharField(choices=[('REGISTRATION', 'Påmeldingsoppdateringer'), ('STRIKE', 'Prikkoppdateringer'), ('EVENT_SIGN_UP_START', 'Arrangementer - påmeldingsstart'), ('EVENT_SIGN_OFF_DEADLINE', 'Arrangementer - avmeldingsfrist'), ('EVENT_EVALUATION', 'Arrangementer - evaluering'), ('EVENT_INFO', 'Arrangementer - info fra arrangør'), ('FINE', 'Grupper - bot'), ('GROUP_MEMBERSHIP', 'Grupper - medlemsskap'), ('OTHER', 'Andre')], max_length=30)),
                ('email', models.BooleanField(default=True)),
                ('website', models.BooleanField(default=True)),
                ('slack', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_notification_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User notification setting',
                'verbose_name_plural': 'User notification settings',
                'ordering': ('notification_type',),
                'unique_together': {('user', 'notification_type')},
            },
        ),
    ]
