# Generated by Django 3.2.10 on 2022-02-10 18:51

import app.communication.models.banner
from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0003_notification_user_related_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.URLField(blank=True, max_length=600, null=True)),
                ('image_alt', models.CharField(blank=True, max_length=200, null=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('visible_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('visible_until', models.DateTimeField(default=app.communication.models.banner.tomorrow)),
                ('url', models.URLField(blank=True, max_length=400, null=True)),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
    ]
