# Generated by Django 3.2.12 on 2022-03-26 22:48

import app.communication.mixins
import app.util.utils
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0004_usernotificationsetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.URLField(blank=True, max_length=600, null=True)),
                ('image_alt', models.CharField(blank=True, max_length=200, null=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('visible_from', models.DateTimeField(default=app.util.utils.now)),
                ('visible_until', models.DateTimeField(default=app.util.utils.tomorrow)),
                ('url', models.URLField(blank=True, max_length=600, null=True)),
            ],
            options={
                'ordering': ('-updated_at',),
            },
            bases=(models.Model, app.communication.mixins.APIBannerErrorsMixin),
        ),
    ]
