# Generated by Django 4.0.4 on 2022-05-12 06:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('communication', '0005_create_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='emails', to=settings.AUTH_USER_MODEL),
        ),
    ]
