# Generated by Django 4.0.8 on 2023-01-30 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0007_remove_sent_mails'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={},
        ),
    ]
