# Generated by Django 4.2.5 on 2023-10-26 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communication", "0008_alter_banner_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usernotificationsetting",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("REGISTRATION", "Påmeldingsoppdateringer"),
                    ("UNREGISTRATION", "Avmeldingsoppdateringer"),
                    ("STRIKE", "Prikkoppdateringer"),
                    ("EVENT_SIGN_UP_START", "Arrangementer - påmeldingsstart"),
                    ("EVENT_SIGN_OFF_DEADLINE", "Arrangementer - avmeldingsfrist"),
                    ("EVENT_EVALUATION", "Arrangementer - evaluering"),
                    ("EVENT_INFO", "Arrangementer - info fra arrangør"),
                    ("FINE", "Grupper - bot"),
                    ("GROUP_MEMBERSHIP", "Grupper - medlemsskap"),
                    ("OTHER", "Andre"),
                ],
                max_length=30,
            ),
        ),
    ]
