# Generated by Django 5.1.1 on 2025-04-10 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communication", "0011_alter_usernotificationsetting_notification_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usernotificationsetting",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("REGISTRATION", "Påmeldingsoppdateringer"),
                    ("UNREGISTRATION", "Avmeldingsoppdateringer"),
                    ("STRIKE", "Prikkoppdateringer"),
                    ("EVENT_SIGN_UP_START", "Arrangementer - påmeldingsstart"),
                    ("EVENT_SIGN_OFF_DEADLINE", "Arrangementer - avmeldingsfrist"),
                    ("EVENT_EVALUATION", "Arrangementer - evaluering"),
                    ("EVENT_INFO", "Arrangementer - info fra arrangør"),
                    ("FINE", "Grupper - bot"),
                    ("GROUP_MEMBERSHIP", "Grupper - medlemsskap"),
                    ("OTHER", "Andre"),
                    ("RESERVATION NEW", "Ny reservasjon"),
                    ("RESERVATION APPROVED", "Godkjent reservasjon"),
                    ("RESERVATION CANCELLED", "Avslått reservasjon"),
                    ("KONTRES", "Kontres"),
                    ("BLITZED", "Blitzed"),
                    ("UTLEGG", "Utlegg"),
                ],
                max_length=30,
            ),
        ),
    ]
