# Generated by Django 5.1.1 on 2026-05-22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("communication", "0012_alter_usernotificationsetting_notification_type"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Warning",
        ),
    ]
