# Generated by Django 3.1.6 on 2021-03-06 00:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyBusiness',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.URLField(blank=True, max_length=600, null=True)),
                ('image_alt', models.CharField(blank=True, max_length=200, null=True)),
                ('business_name', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('year', models.PositiveSmallIntegerField()),
                ('week', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name': 'Weekly business',
                'verbose_name_plural': 'Weekly businesses',
                'ordering': ['year', 'week'],
                'unique_together': {('year', 'week')},
            },
        ),
    ]
