# Generated by Django 3.1.7 on 2021-03-16 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weeklybusiness',
            options={'ordering': ['-year', '-week'], 'verbose_name': 'Weekly business', 'verbose_name_plural': 'Weekly businesses'},
        ),
    ]
