# Generated by Django 3.2.8 on 2021-11-12 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0002_weekly_business_meta'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='JobPost',
                    fields=[
                        ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('image', models.URLField(blank=True, max_length=600, null=True)),
                        ('image_alt', models.CharField(blank=True, max_length=200, null=True)),
                        ('title', models.CharField(max_length=200)),
                        ('ingress', models.CharField(blank=True, default='', max_length=800)),
                        ('body', models.TextField(blank=True, default='')),
                        ('location', models.CharField(max_length=200)),
                        ('deadline', models.DateTimeField(blank=True, null=True)),
                        ('is_continuously_hiring', models.BooleanField(default=False)),
                        ('job_type', models.CharField(choices=[('PART_TIME', 'Deltid'), ('FULL_TIME', 'Fulltid'), ('SUMMER_JOB', 'Sommerjobb'), ('OTHER', 'Andre')], default='OTHER', max_length=30)),
                        ('company', models.CharField(max_length=200)),
                        ('email', models.EmailField(blank=True, max_length=254, null=True)),
                        ('link', models.URLField(blank=True, max_length=300, null=True)),
                        ('class_start', models.IntegerField(choices=[(1, 'First'), (2, 'Second'), (3, 'Third'), (4, 'Forth'), (5, 'Fifth')], default=1)),
                        ('class_end', models.IntegerField(choices=[(1, 'First'), (2, 'Second'), (3, 'Third'), (4, 'Forth'), (5, 'Fifth')], default=5)),
                    ],
                    options={
                        'abstract': False,
                    },
                ),
            ],
            # Table already exists. See app/content/migrations/0032_delete_jobpost.py
            database_operations=[],
        ),
    ]
