# Generated by Django 5.1.1 on 2026-05-22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("career", "0003_jobpost"),
    ]

    operations = [
        migrations.DeleteModel(
            name="WeeklyBusiness",
        ),
    ]
