# Generated by Django 3.2.10 on 2022-02-06 11:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='Badge',
                    fields=[
                        ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('image', models.URLField(blank=True, max_length=600, null=True)),
                        ('image_alt', models.CharField(blank=True, max_length=200, null=True)),
                        ('title', models.CharField(max_length=200)),
                        ('description', models.CharField(max_length=200)),
                    ],
                    options={
                        'verbose_name_plural': 'Badges',
                    },
                ),
                migrations.CreateModel(
                    name='UserBadge',
                    fields=[
                        ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='badge.badge')),
                        ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_badges', to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        'verbose_name': 'User badge',
                        'verbose_name_plural': 'User badges',
                    },
                ),
            ]
        ),
    ]
