# Generated by Django 3.2.10 on 2022-02-17 18:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('badge', '0001_badge_and_user_badge'),
    ]

    operations = [
        migrations.CreateModel(
            name='BadgeCategory',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.URLField(blank=True, max_length=600, null=True)),
                ('image_alt', models.CharField(blank=True, max_length=200, null=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name_plural': 'Badge Categories',
                'ordering': ('created_at',),
            },
        ),
        migrations.AddField(
            model_name='badge',
            name='active_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='badge',
            name='active_to',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='badge',
            name='flag',
            field=models.UUIDField(auto_created=True, default=uuid.uuid4, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='userbadge',
            unique_together={('user', 'badge')},
        ),
        migrations.AddField(
            model_name='badge',
            name='badge_category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='badge.badgecategory'),
        ),
    ]
