# Generated by Django 3.2.10 on 2022-02-24 17:41

from django.db import migrations, models
import uuid

def generate_uuid(apps, schema_editor):
    Badge = apps.get_model('badge', 'badge')
    for row in Badge.objects.all():
        row.flag = uuid.uuid4()
        row.save(update_fields=['flag'])


class Migration(migrations.Migration):

    dependencies = [
        ('badge', '0002_badge_categories'),
    ]

    operations = [
        migrations.RunPython(generate_uuid, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='badge',
            name='flag',
            field=models.UUIDField(auto_created=True, default=uuid.uuid4, serialize=False, unique=True),
        ),
    ]
