#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

mysql_ready() {
python << END
import sys
import os

import MySQLdb

try:
    db_name = os.environ.get("DATABASE_NAME")
    db_user = os.environ.get("DATABASE_USER")
    db_password = os.environ.get("DATABASE_PASSWORD")
    db_host = os.environ.get("DATABASE_HOST")

    db=MySQLdb.connect(host=db_host,user=db_user,
                  passwd=db_password,db=db_name)
except MySQLdb._exceptions.OperationalError as e:
    sys.exit(-1)
sys.exit(0)

END
}
until mysql_ready; do
  >&2 echo 'Waiting for MySQL to become available...'
  sleep 1
done
>&2 echo 'MySQL is available'

exec "$@"
