# Generated by Django 5.1.1 on 2024-10-31 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="file",
            name="url",
        ),
        migrations.AddField(
            model_name="file",
            name="file",
            field=models.URLField(blank=True, max_length=600, null=True),
        ),
    ]
