# Generated by Django 4.0.8 on 2023-05-08 17:04

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0052_event_rules_and_photo_in_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaidEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='paid_information', serialize=False, to='content.event')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('paytime', models.TimeField()),
            ],
            options={
                'verbose_name_plural': 'Paid_events',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.UUIDField(auto_created=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('INITIATE', 'Initiate'), ('RESERVE', 'Reserve'), ('CAPTURE', 'Capture'), ('REFUND', 'Refund'), ('CANCEL', 'Cancel'), ('SALE', 'Sale'), ('VOID', 'Void')], default='INITIATE', max_length=16)),
                ('expire_date', models.DateTimeField(default=datetime.datetime(2023, 5, 8, 18, 4, 11, 846235, tzinfo=utc))),
                ('payment_link', models.URLField(max_length=2000)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='content.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Orders',
                'ordering': ('-created_at',),
            },
        ),
    ]
