# Generated by Django 4.2.5 on 2023-10-17 18:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("content", "0054_registration_payment_expiredate"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PaidEvent",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="paid_information",
                        serialize=False,
                        to="content.event",
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=6)),
                ("paytime", models.TimeField()),
            ],
            options={
                "verbose_name_plural": "Paid_events",
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "order_id",
                    models.UUIDField(
                        auto_created=True,
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("INITIATE", "Initiate"),
                            ("RESERVE", "Reserve"),
                            ("CAPTURE", "Capture"),
                            ("REFUND", "Refund"),
                            ("CANCEL", "Cancel"),
                            ("SALE", "Sale"),
                            ("VOID", "Void"),
                        ],
                        default="INITIATE",
                        max_length=16,
                    ),
                ),
                ("payment_link", models.URLField(max_length=2000)),
                (
                    "event",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders",
                        to="content.event",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Orders",
                "ordering": ("-created_at",),
            },
        ),
    ]
