# Generated by Django 4.0.8 on 2023-02-13 19:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 13, 20, 8, 53, 42208, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_link',
            field=models.URLField(max_length=2000),
        ),
    ]
