# Generated by Django 4.2.5 on 2023-10-18 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="expire_date",
        ),
    ]
