# Generated by Django 4.0.8 on 2023-02-27 15:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_alter_order_expire_date_alter_order_payment_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 27, 16, 56, 4, 146663, tzinfo=utc)),
        ),
    ]
