# Generated by Django 4.0.8 on 2023-02-24 17:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_alter_order_expire_date_alter_order_payment_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 24, 18, 54, 27, 30465, tzinfo=utc)),
        ),
    ]
