# Generated by Django 4.2.5 on 2023-12-17 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0002_remove_order_expire_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("INITIATE", "Initiate"),
                    ("RESERVED", "Reserved"),
                    ("CAPTURE", "Capture"),
                    ("REFUND", "Refund"),
                    ("CANCEL", "Cancel"),
                    ("SALE", "Sale"),
                    ("VOID", "Void"),
                ],
                default="INITIATE",
                max_length=16,
            ),
        ),
    ]
