# Generated by Django 4.0.8 on 2023-08-29 07:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0052_event_rules_and_photo_in_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment', '0002_alter_paidevent_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='content.event'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
