# Generated by Django 4.0.8 on 2023-02-27 16:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_alter_order_expire_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 27, 17, 0, 28, 423339, tzinfo=utc)),
        ),
    ]
