# Generated by Django 4.0.8 on 2023-03-06 16:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_alter_order_expire_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 6, 17, 38, 43, 857115, tzinfo=utc)),
        ),
    ]
