# Generated by Django 4.0.8 on 2023-03-06 16:43

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_alter_order_expire_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='paidevent',
            name='paytime',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 6, 17, 41, 9, 221675, tzinfo=utc)),
        ),
    ]
