# Generated by Django 4.0.8 on 2023-03-09 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_alter_order_expire_date'),
        ('payment', '0005_paidevent_paytime_alter_order_expire_date'),
    ]

    operations = [
    ]
