# Generated by Django 4.0.8 on 2023-03-13 16:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_merge_20230309_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 13, 17, 28, 8, 16598, tzinfo=utc)),
        ),
    ]
