# Generated by Django 4.0.8 on 2023-04-17 15:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_alter_order_expire_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 17, 16, 11, 41, 939882, tzinfo=utc)),
        ),
    ]
