# Generated by Django 4.0.8 on 2023-05-05 15:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0009_alter_order_options_alter_order_expire_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 5, 16, 55, 7, 632999, tzinfo=utc)),
        ),
    ]
