# Generated by Django 4.2.5 on 2024-09-22 19:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("group", "0020_alter_membership_membership_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CodexEvent",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                ("start_date", models.DateTimeField()),
                (
                    "start_registration_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                (
                    "end_registration_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                (
                    "tag",
                    models.CharField(
                        choices=[("Workshop", "Workshop"), ("Lecture", "Lecture")],
                        default="Lecture",
                        max_length=50,
                    ),
                ),
                ("location", models.CharField(max_length=200, null=True)),
                ("mazemap_link", models.URLField(max_length=2000, null=True)),
                (
                    "lecturer",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="codex_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organizer",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="codex_events",
                        to="group.group",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Events",
                "ordering": ("start_date",),
            },
        ),
        migrations.CreateModel(
            name="CodexEventRegistration",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "registration_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("order", models.IntegerField(default=0)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="codex_event_registrations",
                        to="codex.codexevent",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="codex_event_registrations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("order", "created_at"),
                "unique_together": {("user", "event")},
            },
        ),
        migrations.AddField(
            model_name="codexevent",
            name="registrations",
            field=models.ManyToManyField(
                blank=True,
                default=None,
                through="codex.CodexEventRegistration",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
