# Generated by Django 4.2.5 on 2023-12-27 14:29

import app.wrapped.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DataDistributions",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "year",
                    models.CharField(
                        default=app.wrapped.models.set_year,
                        max_length=5,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("events_distribution", models.JSONField()),
                ("fines_distribution", models.JSONField()),
                ("badges_distribution", models.JSONField()),
                ("test_thing", models.CharField(max_length=10)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
