# Generated by Django 4.2.5 on 2023-12-27 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wrapped", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="datadistributions",
            name="test_thing",
        ),
    ]
