# Generated by Django 4.0.8 on 2023-10-03 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kontres', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookableItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='reservation',
            name='bookable_item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='kontres.bookableitem'),
            preserve_default=False,
        ),
    ]
