# Generated by Django 4.2.5 on 2024-02-01 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kontres", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reservation",
            name="description",
        ),
        migrations.AddField(
            model_name="reservation",
            name="accepted_rules",
            field=models.BooleanField(default=True),
        ),
    ]
