# Generated by Django 4.2.5 on 2024-02-19 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kontres", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reservation",
            name="description",
        ),
    ]
