# Generated by Django 4.2.5 on 2024-02-19 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kontres", "0002_remove_reservation_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
