# Generated by Django 4.0.8 on 2023-10-03 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kontres', '0002_bookableitem_reservation_bookable_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='bookable_item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='kontres.bookableitem'),
        ),
    ]
