# Generated by Django 4.2.5 on 2024-02-21 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("group", "0018_fine_defense"),
        ("kontres", "0003_reservation_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reservations",
                to="group.group",
            ),
        ),
    ]
