# Generated by Django 4.2.5 on 2024-02-26 18:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("kontres", "0004_reservation_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookableitem",
            name="allows_alcohol",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="reservation",
            name="alcohol_agreement",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="reservation",
            name="sober_watch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sober_watch_reservations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
