# Generated by Django 4.2.5 on 2024-03-18 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kontres", "0005_bookableitem_allows_alcohol_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="reservation",
            old_name="alcohol_agreement",
            new_name="serves_alcohol",
        ),
    ]
