# Generated by Django 4.2.5 on 2024-03-22 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kontres", "0006_rename_alcohol_agreement_reservation_serves_alcohol"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookableitem",
            name="image",
            field=models.URLField(blank=True, max_length=600, null=True),
        ),
        migrations.AddField(
            model_name="bookableitem",
            name="image_alt",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
