# Generated by Django 4.2.5 on 2024-09-10 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("group", "0018_fine_defense"),
        ("kontres", "0008_reservation_approved_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookableitem",
            name="owner_group",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owner_group",
                to="group.group",
            ),
        ),
        migrations.AddField(
            model_name="reservation",
            name="reason",
            field=models.TextField(blank=True),
        ),
    ]
