# Generated by Django 3.1.2 on 2020-10-30 11:15

import app.common.enums
from django.db import migrations, models
import enumchoicefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.URLField(blank=True, max_length=600, null=True)),
                ('image_alt', models.CharField(blank=True, max_length=200, null=True)),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=200, null=True)),
                ('type', enumchoicefield.fields.EnumChoiceField(default=app.common.enums.GroupType(6), enum_class=app.common.enums.GroupType, max_length=9)),
                ('permissions', models.ManyToManyField(blank=True, related_name='groups_permissions', to='auth.Permission')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
