# Generated by Django 3.1.8 on 2021-04-17 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '004_added_related_name_in_membership'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='permissions',
        ),
    ]
