# Generated by Django 3.1.8 on 2021-04-26 17:53

import app.common.enums
from django.db import migrations
import enumchoicefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('group', '004_added_related_name_in_membership'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='permissions',
        ),
        migrations.AlterField(
            model_name='group',
            name='type',
            field=enumchoicefield.fields.EnumChoiceField(default=app.common.enums.GroupType(7), enum_class=app.common.enums.GroupType, max_length=13),
        ),
    ]
