# Generated by Django 3.1.8 on 2021-05-05 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0006_auto_20210428_1923'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membership',
            options={'ordering': ['user__first_name', 'user__last_name']},
        ),
    ]
