# Generated by Django 3.2.8 on 2021-10-25 13:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('group', '0007_auto_20210505_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershiphistory',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_histories', to='group.group'),
        ),
        migrations.AlterField(
            model_name='membershiphistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_histories', to=settings.AUTH_USER_MODEL),
        ),
    ]
