# Generated by Django 3.2.8 on 2021-11-16 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0008_membership_history_related_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name_plural': 'Groups'},
        ),
    ]
