# Generated by Django 3.2.8 on 2021-12-02 15:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('group', '0009_auto_20211116_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='fine',
            name='reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='group',
            name='fines_activated',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='group',
            name='fines_admin',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='fine_master_groups', to=settings.AUTH_USER_MODEL),
        ),
    ]
