# Generated by Django 3.2.8 on 2021-11-14 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0009_auto_20211114_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fine',
            name='amount',
            field=models.IntegerField(default=1),
        ),
    ]
