# Generated by Django 3.2.8 on 2021-12-02 15:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('group', '0010_auto_20211202_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='fines_admin',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fine_master_groups', to=settings.AUTH_USER_MODEL),
        ),
    ]
