# Generated by Django 3.2.10 on 2022-01-07 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0010_add_laws_and_fines'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='law',
            options={'ordering': ('title',), 'verbose_name_plural': 'Laws'},
        ),
        migrations.RenameField(
            model_name='law',
            old_name='paragraph',
            new_name='title',
        ),
    ]
