# Generated by Django 3.2.8 on 2021-11-14 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0010_alter_fine_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='law',
            name='amount',
            field=models.IntegerField(default=1),
        ),
    ]
