# Generated by Django 3.2.10 on 2022-01-07 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0011_law_rename_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='law',
            options={'ordering': ('paragraph',), 'verbose_name_plural': 'Laws'},
        ),
        migrations.AddField(
            model_name='law',
            name='paragraph',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='law',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
