# Generated by Django 3.2.10 on 2022-02-02 18:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('group', '0012_law_add_paragraph_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='fines_admin',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fine_master_groups', to=settings.AUTH_USER_MODEL),
        ),
    ]
