# Generated by Django 3.2.10 on 2022-01-27 16:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('group', '0013_group_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='members_history',
            field=models.ManyToManyField(blank=True, default=None, related_name='group_members_history', through='group.MembershipHistory', to=settings.AUTH_USER_MODEL, verbose_name='Group membership history'),
        ),
        migrations.AlterField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(blank=True, default=None, related_name='group_members', through='group.Membership', to=settings.AUTH_USER_MODEL, verbose_name='Group members'),
        ),
    ]
