# Generated by Django 3.2.12 on 2022-03-04 15:27

import app.common.enums
from django.db import migrations
import enumchoicefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0014_group_many_to_many'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='type',
            field=enumchoicefield.fields.EnumChoiceField(default=app.common.enums.GroupType(8), enum_class=app.common.enums.GroupType, max_length=13),
        ),
    ]
