# Generated by Django 4.0.3 on 2022-04-21 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0015_alter_group_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='fine',
            name='image',
            field=models.URLField(blank=True, max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='fine',
            name='image_alt',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
