# Generated by Django 3.2.12 on 2022-03-13 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0015_alter_group_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='new_type',
            field=models.CharField(choices=[('TIHLDE', 'Tihlde'), ('Styre', 'Board'), ('Undergruppe', 'Subgroup'), ('Komité', 'Committee'), ('Studieår', 'Studyyear'), ('Studie', 'Study'), ('Interesse Gruppe', 'Interestgroup'), ('Annet', 'Other')], default='Annet', max_length=30),
        ),
    ]
