# Generated by Django 4.0.3 on 2022-04-04 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0015_alter_group_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membershiphistory',
            options={'ordering': ('-end_date', '-start_date'), 'verbose_name': 'Membership History', 'verbose_name_plural': 'Membership Histories'},
        ),
    ]
