# Generated by Django 4.0.4 on 2022-04-29 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0016_fine_image_fine_image_alt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membershiphistory',
            options={'ordering': ('-end_date', '-start_date'), 'verbose_name': 'Membership History', 'verbose_name_plural': 'Membership Histories'},
        ),
    ]
