# Generated by Django 4.0.4 on 2022-05-03 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0017_alter_membershiphistory_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='fine',
            name='defense',
            field=models.TextField(blank=True, default=''),
        ),
    ]
