# Generated by Django 4.2.5 on 2024-09-20 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("group", "0018_fine_defense"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="type",
            field=models.CharField(
                choices=[
                    ("TIHLDE", "TIHLDE"),
                    ("BOARD", "Styre"),
                    ("SUBGROUP", "Undergruppe"),
                    ("COMMITTEE", "Komité"),
                    ("STUDYYEAR", "Studieår"),
                    ("STUDY", "Studie"),
                    ("INTERESTGROUP", "Interesse Gruppe"),
                    ("OTHER", "Annet"),
                ],
                default="OTHER",
                max_length=50,
            ),
        ),
    ]
