# Generated by Django 4.2.5 on 2024-09-20 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("group", "0019_alter_group_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membership",
            name="membership_type",
            field=models.CharField(
                choices=[("LEADER", "Leader"), ("MEMBER", "Member")],
                default="MEMBER",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="membershiphistory",
            name="membership_type",
            field=models.CharField(
                choices=[("LEADER", "Leader"), ("MEMBER", "Member")],
                default="MEMBER",
                max_length=50,
            ),
        ),
    ]
