# Generated by Django 5.1.1 on 2025-08-12 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("group", "0021_alter_group_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="is_private",
            field=models.BooleanField(default=False),
        ),
    ]
