# Generated by Django 5.1.1 on 2025-08-14 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("group", "0022_group_is_private"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="group",
            name="is_private",
        ),
        migrations.AlterField(
            model_name="group",
            name="type",
            field=models.CharField(
                choices=[
                    ("TIHLDE", "TIHLDE"),
                    ("BOARD", "Styre"),
                    ("SUBGROUP", "Undergruppe"),
                    ("COMMITTEE", "Komité"),
                    ("STUDYYEAR", "Studieår"),
                    ("STUDY", "Studie"),
                    ("INTERESTGROUP", "Interesse Gruppe"),
                    ("OTHER", "Annet"),
                    ("PRIVATE", "Privat"),
                ],
                default="OTHER",
                max_length=50,
            ),
        ),
    ]
