# Generated by Django 5.1.1 on 2025-10-27 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("group", "0023_remove_group_is_private_alter_group_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="fine",
            name="starred",
            field=models.BooleanField(default=False),
        ),
    ]
