# Generated by Django 5.1.1 on 2026-03-18 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("group", "0024_fine_starred"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="type",
            field=models.CharField(
                choices=[
                    ("TIHLDE", "TIHLDE"),
                    ("BOARD", "Styre"),
                    ("SUBGROUP", "Undergruppe"),
                    ("COMMITTEE", "Komité"),
                    ("SPORTSTEAM", "Idrettslag"),
                    ("STUDYYEAR", "Studieår"),
                    ("STUDY", "Studie"),
                    ("INTERESTGROUP", "Interesse Gruppe"),
                    ("OTHER", "Annet"),
                    ("PRIVATE", "Privat"),
                ],
                default="OTHER",
                max_length=50,
            ),
        ),
    ]
