# Generated by Django 5.1.1

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("group", "0025_alter_group_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="subtype",
            field=models.CharField(
                blank=True,
                choices=[
                    ("IDRETTSGRUPPE", "Idrettsgruppe"),
                    ("GRUPPE", "Gruppe"),
                ],
                default=None,
                max_length=50,
                null=True,
            ),
        ),
    ]
