# Generated by Django 5.1.1

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("group", "0026_group_subtype"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="group",
            constraint=models.CheckConstraint(
                check=models.Q(subtype__isnull=True)
                | models.Q(type="INTERESTGROUP"),
                name="group_subtype_only_for_interest_groups",
            ),
        ),
    ]
