# Generated by Django 3.1.6 on 2021-02-08 20:35

import app.common.enums
from django.db import migrations, models
import enumchoicefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_membership_membershiphistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='membership_type',
            field=enumchoicefield.fields.EnumChoiceField(default=app.common.enums.MembershipType(2), enum_class=app.common.enums.MembershipType, max_length=6),
        ),
        migrations.AlterField(
            model_name='membershiphistory',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='membershiphistory',
            name='membership_type',
            field=enumchoicefield.fields.EnumChoiceField(default=app.common.enums.MembershipType(2), enum_class=app.common.enums.MembershipType, max_length=6),
        ),
        migrations.AlterField(
            model_name='membershiphistory',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
