name: Changelogger

on:
  pull_request:
    types: [opened]
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    steps:      
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Iterate CHANGELOG
        run: |
          python .github/scripts/changeloger.py
        
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ github.token }}
          title: "docs(changelog): iterate changelog version"
          commit-message: "docs(changelog): iterate changelog version"
          branch: docs/iterate_changelog
          delete-branch: true
          base: dev
