name: CI

on:
  pull_request:
    branches:
      - dev
      - master

  push:
    branches: [ "master" ]

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Code Repository
        uses: actions/checkout@v2

      - name: Set up Python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.6

      - name: Install flake8
        run: |
          python -m pip install --upgrade pip
          pip install flake8 isort black==19.10b0

      - name: Lint with flake8
        run: flake8 app

      - name: Lint with black
        run: black app/ --check --exclude migrations

      - name: Lint with isort
        run: isort . --check-only

  test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: ${{secrets.DATABASE_ROOT_PASSWORD}}
        ports:
          - 3306
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.6

      - name: Install dependencies with pipenv
        run: |
          pip install pipenv
          pipenv install -d

      - name: Run test suite
        run: pipenv run pytest . --cov
        env:
          DJANGO_SECRET: ${{secrets.DJANGO_SECRET}}
          DATABASE_USER: ${{secrets.DATABASE_USER}}
          DATABASE_PASSWORD: ${{secrets.DATABASE_PASSWORD}}
          DATABASE_NAME: ${{secrets.DATABASE_NAME}}
          DATABASE_HOST: ${{secrets.DATABASE_HOST}}
          DATABASE_PORT: ${{ job.services.mysql.ports['3306'] }}