name: CI

# Enable Buildkit and let compose use it to speed up image building
env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1

on:
  pull_request:
    branches:
      - dev
      - master

  push:
    branches: [ "master" ]

jobs:

  flake8:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Code Repository
        uses: actions/checkout@v2

      - name: Set up Python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.6

      - name: Install flake8
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Lint with flake8
        run: flake8

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.6

      - name: Checkout Code Repository
        uses: actions/checkout@v2

      - name: Build the Stack
        run:  docker-compose build

      - name: Make DB Migrations
        run:  docker-compose run --rm -e DJANGO_SECRET=${{secrets.DJANGO_SECRET}} web pipenv run python manage.py migrate

      - name: Run the Stack
        run:  docker-compose up -d

      - name: Run Tests
        run:  docker-compose run --rm -e DJANGO_SECRET=${{secrets.DJANGO_SECRET}} web pipenv run pytest

      - name: Tear down the Stack
        run:  docker-compose down