name: Deploy to Azure development

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  deploy:
    uses: TIHLDE/Lepton/.github/workflows/deploy_to_azure.yml@dev
    with:
      registry_name: leptonregistrydev
    secrets:
      registry_username: ${{ secrets.ACI_DEV_USERNAME }}
      registry_password: ${{ secrets.ACI_DEV_PASSWORD }}
