name: Deploy to Azure production

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    uses: TIHLDE/Lepton/.github/workflows/deploy_to_azure.yml@master
    with:
      registry_name: leptonregistrypro
    secrets:
      registry_username: ${{ secrets.ACI_PROD_USERNAME }}
      registry_password: ${{ secrets.ACI_PROD_PASSWORD }}
