name: Test and linting

on:
  pull_request:
    branches:
      - dev
      - master
jobs:
  test_and_lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.6

      - name: Install dependencies with pipenv
        run: |
          pip install pipenv
          pipenv install

      - run: pipenv run isort . --check-only
      - run: pipenv run black app/ --check
      - run: pipenv run flake8 app
#       Temporarily disabled until tests are stable
#      - run: pipenv run pytest --cov