name: Update Pipfile.lock
on:
  pull_request:
    branches:
      - dev

jobs:
  check_should_skip:
    name: Check if Pipfile has been updated
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@master
        with:
          github_token: ${{ github.token }}
          cancel_others: 'false'
          paths: '["**/Pipfile"]'

  update_pipfile_lock:
    needs: check_should_skip
    if: ${{ needs.check_should_skip.outputs.should_skip != 'true' }}
    name: Update Pipfile.lock
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Install dependencies with pipenv
        run: pip install pipenv

      - name: Update Pipfile.lock
        run: pipenv lock

      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          message: 'chore(pipfile): update pipfile.lock'
